package bat.example;
// Generated 23-Feb-2017 18:35:49 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * IssueInfo generated by hbm2java
 */
public class IssueInfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer issueId;
	private int studentId;
	private int bookId;
	private Date dateIssue;
	private Date dateReturn;

	public IssueInfo()
	{
	}

	public IssueInfo(int studentId, int bookId, Date dateIssue)
	{
		this.studentId = studentId;
		this.bookId = bookId;
		this.dateIssue = dateIssue;
	}

	public IssueInfo(int studentId, int bookId, Date dateIssue, Date dateReturn)
	{
		this.studentId = studentId;
		this.bookId = bookId;
		this.dateIssue = dateIssue;
		this.dateReturn = dateReturn;
	}

	public Integer getIssueId()
	{
		return this.issueId;
	}

	public void setIssueId(Integer issueId)
	{
		this.issueId = issueId;
	}

	public int getStudentId()
	{
		return this.studentId;
	}

	public void setStudentId(int studentId)
	{
		this.studentId = studentId;
	}

	public int getBookId()
	{
		return this.bookId;
	}

	public void setBookId(int bookId)
	{
		this.bookId = bookId;
	}

	public Date getDateIssue()
	{
		return this.dateIssue;
	}

	public void setDateIssue(Date dateIssue)
	{
		this.dateIssue = dateIssue;
	}

	public Date getDateReturn()
	{
		return this.dateReturn;
	}

	public void setDateReturn(Date dateReturn)
	{
		this.dateReturn = dateReturn;
	}

}
