package bat.example;
// Generated 23-Feb-2017 18:35:49 by Hibernate Tools 3.5.0.Final

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int studentId;
	private String name;
	private String department;
	private String password;
	private String email;

	public Student()
	{
	}

	public Student(int studentId, String name, String department, String password, String email)
	{
		this.studentId = studentId;
		this.name = name;
		this.department = department;
		this.password = password;
		this.email = email;
	}

	public int getStudentId()
	{
		return this.studentId;
	}

	public void setStudentId(int studentId)
	{
		this.studentId = studentId;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getDepartment()
	{
		return this.department;
	}

	public void setDepartment(String department)
	{
		this.department = department;
	}

	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

}
